# Attribute Numpy
dimension  : melihat dimensi array

Shape : mengetahui jumlah baris dan kolom

type : mengetahui type data di array

itemsize : melihat ukuran memori yang dipakai array

nbytes : total bytes satu array

In [21]:
import numpy as np

my_numpy = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 0],
                     [11, 12, 13, 14, 15]
                    ])

print(my_numpy)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]


In [11]:
# dimensi
# list[x] = dimensi 1
# list[x][y] = dimensi 2
my_numpy.ndim

2

In [23]:
# shape
my_numpy.shape

(3, 5)

In [14]:
# type
my_numpy.dtype

dtype('int64')

In [15]:
# itemsize
my_numpy.itemsize

8

In [16]:
# nbytes
my_numpy.nbytes

80

## Indexing Arrays


In [17]:
my_numpy[1][2:]

array([8, 9, 0])

## slicing array

In [18]:
# [start: stop: step]
nmp = np.array(range(10))
print(nmp)
nmp[0: 6: 2]

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4])

In [22]:
# multidimension
my_numpy[1: ,2:]
# 1: (my_numpy[1-selesai])
# 2: (my_numpy[1-selesai][2-selesai])


array([[ 8,  9,  0],
       [13, 14, 15]])

## reshaping array
menukar kolom dan baris, awalnya 5, 2 jadi 2, 5

In [24]:
my_numpy.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12],
       [13, 14, 15]])

## Joining Array

In [25]:
nmpy = np.array([[16, 17, 18, 19, 20]])

np.concatenate([my_numpy, nmpy])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Objek Pandas
series = objek 1 dimensi

dataframe = objek 2 dimensi mirip seperti table

## Series


In [31]:
import pandas as pd
x = pd.Series([6, 3, 4, 6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64
[90, 80]


index = paling kiri 0-3
### Cara merubah index

In [27]:
# cara pertama
x.index = ['a', 'b', 'c', 'd']
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [28]:
# cara kedua
x = pd.Series([6, 3, 4, 6], index=['a', 'b', 'c', 'd'])
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [29]:
# check tipe data
print(type(x))

<class 'pandas.core.series.Series'>


## Membaca data dari File

In [ ]:
# # membaca dari csv
# df_from_csv = pd.read_csv('jabar-corona-virus-case.csv')

# # membaca dari excel
# df_from_excel = pd.read_excel('xxx.xlsx')

## Pemeriksaan sederhana tentang karakteristik data

* head() = secara default melihat 5 data pertama
* tail() = secara default melihat 5 data terakhir
* info()
* describe()